#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP_ID="com.winlator.cmod"
IMAGEFS_ABS="/data/data/${APP_ID}/files/imagefs"
UPSTREAM_APP_COMMIT="4f55d117fff1542944e5b91f433470445160ce08"
VORTEK_CLIENT_COMMIT="b1730c5def9b575672e671aee11d79ae7adc63d1"
VORTEK_ASSET="${ROOT_DIR}/app/src/main/assets/graphics_driver/vortek-2.1-cmod.tzst"
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "${TMP_DIR}"' EXIT

log() {
    printf '[prepare-vortek] %s\n' "$*"
}

checkout_commit() {
    local url="$1"
    local commit="$2"
    local dst="$3"
    git init -q "$dst"
    git -C "$dst" remote add origin "$url"
    git -C "$dst" fetch -q --depth=1 origin "$commit"
    git -C "$dst" checkout -q --detach FETCH_HEAD
}

for cmd in git cmake python3 tar zstd aarch64-linux-gnu-gcc; do
    command -v "$cmd" >/dev/null 2>&1 || {
        echo "Missing required command: $cmd" >&2
        exit 1
    }
done

log "Fetching pinned upstream Winlator Vortek server"
UPSTREAM_APP="${TMP_DIR}/winlator-app"
checkout_commit "https://github.com/brunodev85/winlator-app.git" "$UPSTREAM_APP_COMMIT" "$UPSTREAM_APP"

# The cmod tree predates upstream's split native layout. Keep the current cmod
# winlator target, but import only the Vortek server and the small utility pieces
# that Vortek expects from the new native tree.
rm -rf "${ROOT_DIR}/app/src/main/cpp/vortekrenderer"
cp -a "${UPSTREAM_APP}/app/src/main/cpp/vortekrenderer" "${ROOT_DIR}/app/src/main/cpp/vortekrenderer"
rm -rf "${ROOT_DIR}/app/src/main/cpp/winlator/include"
mkdir -p "${ROOT_DIR}/app/src/main/cpp/winlator/include"
cp -a "${UPSTREAM_APP}/app/src/main/cpp/winlator/include/." "${ROOT_DIR}/app/src/main/cpp/winlator/include/"
mkdir -p "${ROOT_DIR}/app/src/main/cpp/vortekrenderer/compat"
cp "${UPSTREAM_APP}/app/src/main/cpp/winlator/src/arrays.c" \
   "${ROOT_DIR}/app/src/main/cpp/vortekrenderer/compat/arrays.c"
cp "${UPSTREAM_APP}/app/src/main/cpp/winlator/src/ring_buffer.c" \
   "${ROOT_DIR}/app/src/main/cpp/vortekrenderer/compat/ring_buffer.c"

ROOT_DIR="$ROOT_DIR" APP_ID="$APP_ID" IMAGEFS_ABS="$IMAGEFS_ABS" python3 <<'PY'
import os
from pathlib import Path

root = Path(os.environ["ROOT_DIR"])
app_id = os.environ["APP_ID"]
imagefs = os.environ["IMAGEFS_ABS"]

# Patch all imported Vortek/native helper text for cmod's application id and
# imagefs location. Upstream binaries/assets hard-code com.winlator/rootfs.
for base in (root / "app/src/main/cpp/vortekrenderer", root / "app/src/main/cpp/winlator/include"):
    for path in base.rglob("*"):
        if not path.is_file():
            continue
        try:
            text = path.read_text()
        except UnicodeDecodeError:
            continue
        text = text.replace("/data/data/com.winlator/files/rootfs", imagefs)
        text = text.replace("/data/data/com.winlator/cache", f"/data/data/{app_id}/cache")
        text = text.replace(
            "Java_com_winlator_xenvironment_components_VortekRendererComponent_",
            "Java_com_winlator_cmod_xenvironment_components_VortekRendererComponent_",
        )
        path.write_text(text)

cmake = root / "app/src/main/cpp/vortekrenderer/CMakeLists.txt"
text = cmake.read_text()
text = text.replace("../libadrenotools/include", "../adrenotools/include")
if "compat/arrays.c" not in text:
    text = text.replace(
        "            src/main.c\n",
        "            src/main.c\n"
        "            compat/arrays.c\n"
        "            compat/ring_buffer.c\n",
        1,
    )
cmake.write_text(text)

root_cmake = root / "app/src/main/cpp/CMakeLists.txt"
text = root_cmake.read_text()
if "add_subdirectory(vortekrenderer)" not in text:
    marker = "add_subdirectory(adrenotools)"
    if marker not in text:
        raise SystemExit("Could not locate adrenotools subdirectory marker in native CMakeLists.txt")
    text = text.replace(
        marker,
        marker + "\n\n# Vortek host renderer (generated by scripts/prepare-vortek.sh)\n"
        "if(EXISTS \"${CMAKE_CURRENT_SOURCE_DIR}/vortekrenderer/CMakeLists.txt\")\n"
        "    add_subdirectory(vortekrenderer)\n"
        "endif()",
        1,
    )
root_cmake.write_text(text)
PY

log "Building Vortek guest Vulkan ICD for cmod imagefs"
VORTEK_CLIENT="${TMP_DIR}/vortek-client"
checkout_commit "https://github.com/brunodev85/vortek.git" "$VORTEK_CLIENT_COMMIT" "$VORTEK_CLIENT"

VORTEK_CLIENT="$VORTEK_CLIENT" APP_ID="$APP_ID" IMAGEFS_ABS="$IMAGEFS_ABS" python3 <<'PY'
import os
from pathlib import Path

root = Path(os.environ["VORTEK_CLIENT"])
app_id = os.environ["APP_ID"]
imagefs = os.environ["IMAGEFS_ABS"]
for path in root.rglob("*"):
    if not path.is_file() or ".git" in path.parts:
        continue
    try:
        text = path.read_text()
    except UnicodeDecodeError:
        continue
    text = text.replace("/data/data/com.winlator/files/rootfs", imagefs)
    text = text.replace("/data/data/com.winlator/cache", f"/data/data/{app_id}/cache")
    path.write_text(text)
PY

cmake -S "$VORTEK_CLIENT" -B "${VORTEK_CLIENT}/build-cmod" \
    -DCMAKE_SYSTEM_NAME=Linux \
    -DCMAKE_SYSTEM_PROCESSOR=aarch64 \
    -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_C_FLAGS_RELEASE="-O2 -Wl,-rpath=${IMAGEFS_ABS}/usr/lib"
cmake --build "${VORTEK_CLIENT}/build-cmod" --parallel

VORTEK_LIB="${VORTEK_CLIENT}/build-cmod/libvulkan_vortek.so"
if [[ ! -f "$VORTEK_LIB" ]]; then
    echo "Vortek client build did not produce $VORTEK_LIB" >&2
    exit 1
fi

STAGE="${TMP_DIR}/vortek-asset"
mkdir -p "${STAGE}/usr/lib" "${STAGE}/usr/share/vulkan/icd.d"
cp "$VORTEK_LIB" "${STAGE}/usr/lib/libvulkan_vortek.so"
cat > "${STAGE}/usr/share/vulkan/icd.d/vortek_icd.aarch64.json" <<EOF
{
    "ICD": {
        "api_version": "1.1.128",
        "library_path": "${IMAGEFS_ABS}/usr/lib/libvulkan_vortek.so"
    },
    "file_format_version": "1.0.0"
}
EOF
mkdir -p "$(dirname "$VORTEK_ASSET")"
rm -f "$VORTEK_ASSET"
tar --zstd -cf "$VORTEK_ASSET" -C "$STAGE" .

log "Patching cmod UI/runtime wiring"
ROOT_DIR="$ROOT_DIR" python3 <<'PY'
from pathlib import Path
import os

root = Path(os.environ["ROOT_DIR"])

arrays = root / "app/src/main/res/values/arrays.xml"
text = arrays.read_text()
if "<item>Vortek</item>" not in text:
    old = """    <string-array name=\"graphics_driver_entries\">\n        <item>Wrapper</item>\n    </string-array>"""
    new = """    <string-array name=\"graphics_driver_entries\">\n        <item>Wrapper</item>\n        <item>Vortek</item>\n    </string-array>"""
    if old not in text:
        raise SystemExit("Could not patch graphics_driver_entries")
    text = text.replace(old, new, 1)
arrays.write_text(text)

activity = root / "app/src/main/java/com/winlator/cmod/XServerDisplayActivity.java"
text = activity.read_text()

import_marker = "import com.winlator.cmod.xenvironment.components.GuestProgramLauncherComponent;\n"
import_line = "import com.winlator.cmod.xenvironment.components.VortekRendererComponent;\n"
if import_line not in text:
    if import_marker not in text:
        raise SystemExit("Could not locate GuestProgramLauncherComponent import")
    text = text.replace(import_marker, import_marker + import_line, 1)

# Vortek callbacks can ask the XServer for its active renderer. Older cmod had
# the setter but never populated it.
view_marker = """        final XServerRendererView renderer = xServerView;\n        renderer.setCursorVisible(false);"""
if "xServer.setXServerView(xServerView);" not in text:
    if view_marker not in text:
        raise SystemExit("Could not locate XServer renderer initialization")
    text = text.replace(
        view_marker,
        "        xServer.setXServerView(xServerView);\n" + view_marker,
        1,
    )

method_marker = "    private void extractGraphicsDriverFiles() {\n"
if "private boolean isVortekGraphicsDriver()" not in text:
    helper = r'''    private boolean isVortekGraphicsDriver() {
        return "vortek".equalsIgnoreCase(graphicsDriver);
    }

    private void installVortekGraphicsDriver(File rootDir) {
        File marker = new File(rootDir, "usr/lib/.winlator-vortek-2.1-cmod");
        if (firstTimeBoot || !marker.isFile()) {
            Log.i("GraphicsDriverExtraction", "Installing Vortek 2.1 cmod guest ICD");
            boolean extracted = TarCompressorUtils.extract(
                    TarCompressorUtils.Type.ZSTD,
                    this,
                    "graphics_driver/vortek-2.1-cmod.tzst",
                    rootDir);
            if (!extracted) {
                throw new IllegalStateException("Failed to extract Vortek guest Vulkan ICD");
            }
            FileUtils.writeString(marker, "vortek=2.1;layout=cmod-imagefs-v1");
        }
        envVars.put("VK_ICD_FILENAMES",
                imageFs.getShareDir() + "/vulkan/icd.d/vortek_icd.aarch64.json");
    }

'''
    if method_marker not in text:
        raise SystemExit("Could not locate extractGraphicsDriverFiles")
    text = text.replace(method_marker, helper + method_marker, 1)

# Vortek owns the guest Vulkan ICD path; don't continue into the Wrapper ICD
# configuration after setting DXVK/WineD3D variables.
branch_marker = """        File rootDir = imageFs.getRootDir();\n\n        if (dxwrapper.contains(\"dxvk\")) {"""
if "installVortekGraphicsDriver(rootDir);" not in text:
    branch = r'''        File rootDir = imageFs.getRootDir();

        if (isVortekGraphicsDriver()) {
            if (dxwrapper.contains("dxvk")) {
                DXVKConfigDialog.setEnvVars(this, dxwrapperConfig, envVars);
                String dxvkVersion = dxwrapperConfig.get("version");
                if ("1.11.1-sarek".equals(dxvkVersion)) {
                    envVars.put("WRAPPER_NO_PATCH_OPCONSTCOMP", "1");
                }
            } else {
                WineD3DConfigDialog.setEnvVars(this, dxwrapperConfig, envVars);
            }
            installVortekGraphicsDriver(rootDir);
            // OpenGL goes through Zink -> Vortek while Vulkan/DXVK use Vortek directly.
            extractOpenGLDriver(rootDir);
            return;
        }

        if (dxwrapper.contains("dxvk")) {'''
    if branch_marker not in text:
        raise SystemExit("Could not locate graphics extraction root marker")
    text = text.replace(branch_marker, branch, 1)

xserver_marker = """        environment.addComponent(\n                new XServerComponent(\n                        xServer,\n                        UnixSocketConfig.createSocket(rootPath, UnixSocketConfig.XSERVER_PATH)));\n\n        if (audioDriver.equals(\"alsa\")) {"""
if "new VortekRendererComponent(" not in text:
    insertion = r'''        environment.addComponent(
                new XServerComponent(
                        xServer,
                        UnixSocketConfig.createSocket(rootPath, UnixSocketConfig.XSERVER_PATH)));

        if (isVortekGraphicsDriver()) {
            VortekRendererComponent.Options vortekOptions =
                    VortekRendererComponent.Options.fromConfig(this, graphicsDriverConfig);
            environment.addComponent(new VortekRendererComponent(
                    xServer,
                    UnixSocketConfig.createSocket(rootPath, VortekRendererComponent.SERVER_PATH),
                    vortekOptions));
        }

        if (audioDriver.equals("alsa")) {'''
    if xserver_marker not in text:
        raise SystemExit("Could not locate XServer component marker")
    text = text.replace(xserver_marker, insertion, 1)

activity.write_text(text)
PY

log "Vortek cmod integration prepared successfully"
log "guest asset: ${VORTEK_ASSET}"
